### ISSUE TITLE
Using "it" and pseudo-english is a tad confusing

### ISSUE THREAD

**Issue by whot** [ebassi/mutest#5]
This took me a bit too long to figure out, so let's file a bug for it.

I expected "it" to be an acronym or abbreviation and could not figure out what it stood for ("iterator"??). Eventually, after searching Jasmin docs and the examples I understood that it's supposed to create an English pseudosentence.

like here:
```
mutest_it ("contains at least a spec with an expectation", general_spec);
```

A bit weird, but ok. It clashes with the other main entry point though, `mutest_expect`

```
mutest_expect ("str contains 'hello'", ...
```
I don't think "expect str contains hello" is correct English either, though as ESL speaker I guess I'm not the authority here. But digging further, this pseudo-english gets a bit worse, see e.g. the  [Jasmine docs](https://jasmine.github.io/tutorials/your_first_suite):
```
 it("and has a positive case", function() {
    expect(true).toBe(true);
  });
```

So this is not a disagreement with the general structure, but I don't think forcing pseudo-English here is a good idea. I consider it more confusing than helpful and since you need all the prefixes for C anyway, maybe consider using `mutest_expect, mutest_suite, mutest_spec` or something more self-explanatory?

**Comment by ebassi** [comment]
Thanks for the feedback, it's very much appreciated.

> but I don't think forcing pseudo-English here is a good idea.

Well, that's the whole point of the design, so as a matter of fact I do think it's a good idea. ;-)

The overall design of the API is based on [Behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development), which uses a "pseudo natural" DSL. The goal is to write down the specification of a class in plain text, in terms of expected behavior, and then turn it into code with minimal additions, so that the textual output of the test suite closely matches the textual source.

It's, of course, a bit easier if you are using a high level language that can define a DSL, but the point still stands even with a verbose language like C.

For instance, this is an example taken from the Wikipedia page, using Ruby/RSpec:

```ruby
describe Hash do
  let(:hash) { Hash[:hello, 'world'] }

  it { expect(Hash.new).to eq({}) }

  it "hashes the correct information in a key" do
    expect(hash[:hello]).to eq('world')
  end

  it 'includes key' do
    hash.keys.include?(:hello).should be true
  end
end
```

Which produces something along the lines of:

```
 Hash
   should eq {}
   includes key
   hashes the correct information in a key
```

The nice property of this design is that it allows me to:

 - know what the expectations of the Hash type are just from reading the test log, even without reading the API reference or the source code
 - read the test code and immediately grasp the expectations, even without known Ruby

Another design goal is to write test suites that are documented in their code, without necessarily leaving comments that will inevitably go out of sync (if comments are left at all). For instance, in GLib's testing API we recently had to add a [`g_test_summary()`](https://gitlab.gnome.org/GNOME/glib/issues/1450) function to describe the tests in the log, to ensure that the intent of test is documented. This is basically what `mutest_expect()` already provides, and forces you to do. The RSpec example above can generate a description of the specification because it knows what kind of matchers have been called, which is something we cannot do in C, but I think writing down something is a small price to pay.

The Jasmine docs are kind of bad, since they try to be discursive instead of being descriptive—i.e. they end up being the text of the example, instead of describing the example's specification. For instance, that example should really be written as:

```js
  it("should have a positive case", function() { expect(true).toBe(true); });
```

But, of course, that breaks the sentence flow in the documentation.

I freely admit that my examples are **also** kind of bad, and I'm going to change them before hitting 1.0. I've been writing assert()-based test cases for the past 10 years, so switching to expectations and specifications isn't as natural as it ought to be. The string test in the example above ought to be:

```cpp
mutest_expect ("str to contain 'hello'", …);
```

Outside of the general design considerations, another reason why I won't change the API is that every other BDD-based test framework follows the same naming policies: they all use `describe`, `it`, and `expect`. Changing them to be old school C adds cognitive load, and leads to text output that's basically just "assert that this is true" instead of describing what the intent is.

So, **tl;dr**: the whole point of this API is to enforce a pseudo-natural language to describe tests, and changing the names of the API would defeat that purpose.

**Comment by whot** [comment]
definitely not the hill I'm going to die on or even start searching for windmills, but at least to me the pseudo-english has a higher cognitive load than 'normal' terms. Either way, thanks for the long explanation, much appreciated.
