### ISSUE TITLE
Automatically terminate mutest_expect()?

### ISSUE THREAD

**Issue by whot** [ebassi/mutest#6]
If a `mutest_expect()` call isn't null-terminated, the compiler throws a warning. But since `mutest_expect` is a macro anyway, we could just automatically NULL-terminate the argument list by adding NULL as last argument:

```
#define mutest_expect(description,value,expect_func,...) \
    mutest_expect_full (__FILE__, __LINE__, __func__, \
                        description, value, expect_func, \
                        __VA_ARGS__, NULL) 
```
Makes the API a bit more straightforward to use.

**Comment by ebassi** [comment]
This is a very good idea. :+1:

**Comment by ebassi** [comment]
Ah, now I remember why I didn't do it.

Some matchers are unary; for instance:

 - `mutest_to_be_true`
 - `mutest_to_be_false`
 - `mutest_to_be_null`
 - `mutest_skip`

Which means that if you do something like:

```cpp
  mutest_expect ("a to be true", mutest_bool_value (a), mutest_to_be_true);
```

The compiler will error out with:

```
../include/mutest.h:663:97: error: expected expression before ‘,’ token
  663 |   mutest_expect_full (__FILE__, __LINE__, __func__, description, value, expect_func, __VA_ARGS__, NULL)
      |                                                                                                 ^
```

Because the `expect_func` is not part of the `__VA_ARGS__`. I could probably move `expect_func` into `__VA_ARGS__` and see if that does the trick…

**Comment by whot** [comment]
There's `__VA_OPT__`  but I suspect that's not portable enough.

I'm closing this, the only other options I see here are:
- dropping unary matchers which would work for the true/false/null ones but that's going to restrict you in the future
- some other hack with multiple layers of expansion

Given that detecting a missing `NULL` is reliable and can produce a warning but anything else is likely going to be nasty it's not worth worrying about it.
